name: Free VPS with WireGuard VPN

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up VPS with WireGuard
        run: |
          sudo apt update
          sudo apt install -y wireguard qrencode
          sudo modprobe wireguard
          sudo sysctl -w net.ipv4.ip_forward=1
          sudo sysctl -w net.ipv6.conf.all.forwarding=1

          SERVER_PRIV_KEY=$(wg genkey)
          SERVER_PUB_KEY=$(echo $SERVER_PRIV_KEY | wg pubkey)
          CLIENT_PRIV_KEY=$(wg genkey)
          CLIENT_PUB_KEY=$(echo $CLIENT_PRIV_KEY | wg pubkey)

          SERVER_IP="10.0.0.1"
          CLIENT_IP="10.0.0.2"
          SERVER_PORT=51820

          echo "[Interface]
          Address = $SERVER_IP/24
          ListenPort = $SERVER_PORT
          PrivateKey = $SERVER_PRIV_KEY
          PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
          PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
          " | sudo tee /etc/wireguard/wg0.conf

          echo "[Peer]
          PublicKey = $CLIENT_PUB_KEY
          AllowedIPs = $CLIENT_IP/32
          " | sudo tee -a /etc/wireguard/wg0.conf

          sudo systemctl start wg-quick@wg0
          sudo systemctl enable wg-quick@wg0

          echo "[Interface]
          PrivateKey = $CLIENT_PRIV_KEY
          Address = $CLIENT_IP/24
          DNS = 1.1.1.1

          [Peer]
          PublicKey = $SERVER_PUB_KEY
          Endpoint = $(curl -s ifconfig.me):$SERVER_PORT
          AllowedIPs = 0.0.0.0/0
          PersistentKeepalive = 25
          " > client.conf

          qrencode -t ansiutf8 < client.conf
          echo "Scan the above QR code with your WireGuard app."
          echo "Or manually configure using the following settings:"
          cat client.conf

          sleep 86400
