name: Free VPS WireGuard VPN

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup VPS
      run: |
        sudo apt update && sudo apt install -y wireguard curl wget qrencode
        wg genkey | tee privatekey | wg pubkey > publickey
        SERVER_PRIV=$(cat privatekey)
        SERVER_PUB=$(cat publickey)
        
        CLIENT_PRIV=$(wg genkey)
        CLIENT_PUB=$(echo $CLIENT_PRIV | wg pubkey)
        
        SERVER_IP="10.66.66.1"
        CLIENT_IP="10.66.66.2"

        echo "[Interface]
Address = $SERVER_IP/24
ListenPort = 51820
PrivateKey = $SERVER_PRIV

[Peer]
PublicKey = $CLIENT_PUB
AllowedIPs = $CLIENT_IP/32" > wg0.conf

        sudo mv wg0.conf /etc/wireguard/
        sudo chmod 600 /etc/wireguard/wg0.conf
        sudo wg-quick up wg0
        
        echo "[Interface]
PrivateKey = $CLIENT_PRIV
Address = $CLIENT_IP/32
DNS = 1.1.1.1

[Peer]
PublicKey = $SERVER_PUB
Endpoint = $(curl -s ifconfig.me):51820
AllowedIPs = 0.0.0.0/0, ::/0" > client.conf

        echo "========== VPN CONFIG =========="
        cat client.conf
        
        echo "========== QR CODE =========="
        qrencode -t ansiutf8 < client.conf

        sleep 86400
